import type { AccountSubtype, AccountType } from '@global-wakili/database';

export type ChartOfAccountSeed = {
  code: string;
  name: string;
  type: AccountType;
  subtype: AccountSubtype;
  allowManualPosting: boolean;
  isSystem: boolean;
  isActive: boolean;
  currency?: string | null;
  description?: string | null;
};

export const LEGAL_CHART_OF_ACCOUNTS_SEED: ChartOfAccountSeed[] = [
  {
    code: '1000',
    name: 'Office Bank Account',
    type: 'ASSET',
    subtype: 'OFFICE_BANK',
    allowManualPosting: true,
    isSystem: true,
    isActive: true,
    description: 'Primary firm operating bank account',
  },
  {
    code: '1010',
    name: 'Client Trust Bank Account',
    type: 'ASSET',
    subtype: 'TRUST_BANK',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Client money held in trust under Advocates Accounts Rules',
  },
  {
    code: '1100',
    name: 'Accounts Receivable',
    type: 'ASSET',
    subtype: 'ACCOUNTS_RECEIVABLE',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Trade receivables from client invoices',
  },
  {
    code: '1110',
    name: 'Disbursement Recoverable',
    type: 'ASSET',
    subtype: 'DISBURSEMENT_ASSET',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Client disbursements recoverable from matters',
  },
  {
    code: '2000',
    name: 'Accounts Payable',
    type: 'LIABILITY',
    subtype: 'ACCOUNTS_PAYABLE',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Trade payables to suppliers and vendors',
  },
  {
    code: '2010',
    name: 'Client Trust Liability',
    type: 'LIABILITY',
    subtype: 'TRUST_LIABILITY',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Amount owed back to clients from trust funds',
  },
  {
    code: '2020',
    name: 'Retainer Liability',
    type: 'LIABILITY',
    subtype: 'RETAINER_LIABILITY',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Unused advance retainers received from clients',
  },
  {
    code: '2100',
    name: 'VAT Output',
    type: 'LIABILITY',
    subtype: 'VAT_OUTPUT',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Output VAT collected on taxable invoices',
  },
  {
    code: '2110',
    name: 'VAT Input',
    type: 'ASSET',
    subtype: 'VAT_INPUT',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Recoverable input VAT from supplier bills',
  },
  {
    code: '2200',
    name: 'PAYE Liability',
    type: 'LIABILITY',
    subtype: 'PAYE_LIABILITY',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'PAYE withheld pending remittance',
  },
  {
    code: '2210',
    name: 'NSSF Liability',
    type: 'LIABILITY',
    subtype: 'NSSF_LIABILITY',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'NSSF deductions and employer contributions pending remittance',
  },
  {
    code: '2220',
    name: 'SHIF Liability',
    type: 'LIABILITY',
    subtype: 'SHIF_LIABILITY',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'SHIF deductions pending remittance',
  },
  {
    code: '2230',
    name: 'Housing Levy Liability',
    type: 'LIABILITY',
    subtype: 'HOUSING_LEVY_LIABILITY',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Housing levy deductions and employer portion pending remittance',
  },
  {
    code: '3000',
    name: 'Suspense Account',
    type: 'EQUITY',
    subtype: 'SUSPENSE',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Temporary balancing account for controlled exception handling only',
  },
  {
    code: '4000',
    name: 'Legal Fees Income',
    type: 'INCOME',
    subtype: 'LEGAL_FEES_INCOME',
    allowManualPosting: false,
    isSystem: true,
    isActive: true,
    description: 'Income recognized from professional legal services',
  },
  {
    code: '5000',
    name: 'General Operating Expense',
    type: 'EXPENSE',
    subtype: 'GENERAL_EXPENSE',
    allowManualPosting: true,
    isSystem: true,
    isActive: true,
    description: 'General office and operating expenses',
  },
];