// apps/api/src/modules/platform/PlatformPermissionMap.ts

export const PLATFORM_PERMISSION_KEYS = {
  viewOverview: 'platform.view_overview',
  manageUsers: 'platform.manage_users',
  viewUsers: 'platform.view_users',
  manageTenantLifecycle: 'platform.manage_tenant_lifecycle',
  viewTenantLifecycle: 'platform.view_tenant_lifecycle',
  manageBilling: 'platform.manage_billing',
  viewBilling: 'platform.view_billing',
  manageQuotas: 'platform.manage_quotas',
  viewQuotas: 'platform.view_quotas',
  manageFlags: 'platform.manage_flags',
  viewFlags: 'platform.view_flags',
  manageSettings: 'platform.manage_settings',
  viewSettings: 'platform.view_settings',
  manageImpersonation: 'platform.manage_impersonation',
  viewImpersonation: 'platform.view_impersonation',
  manageIncidents: 'platform.manage_incidents',
  viewIncidents: 'platform.view_incidents',
  manageBackups: 'platform.manage_backups',
  viewBackups: 'platform.view_backups',
  viewWebhooks: 'platform.view_webhooks',
  manageHealth: 'platform.manage_health',
  viewHealth: 'platform.view_health',
  manageTickets: 'platform.manage_tickets',
  viewTickets: 'platform.view_tickets',
  manageMessaging: 'platform.manage_messaging',
  viewMessaging: 'platform.view_messaging',
  managePatches: 'platform.manage_patches',
  viewPatches: 'platform.view_patches',
  manageQueueOps: 'platform.manage_queue_ops',
  viewQueueOps: 'platform.view_queue_ops',
} as const;