export const AUDIT_REQUIRED_ACTIONS = [
  // Authentication
  'LOGIN_SUCCESS',
  'LOGIN_FAILED',
  'PASSWORD_CHANGED',
  'MFA_ENABLED',
  'MFA_DISABLED',

  // Trust accounting (Law Society compliance)
  'TRUST_DEPOSIT',
  'TRUST_WITHDRAWAL',
  'TRUST_TRANSFER',
  'TRUST_REVERSAL',
  'TRUST_RECONCILIATION_COMPLETED',
  'TRUST_RECONCILIATION_FAILED',

  // Financial ledger integrity
  'JOURNAL_POSTED',
  'JOURNAL_REVERSED',
  'PAYMENT_ALLOCATED',
  'PAYMENT_UNALLOCATED',
  'INVOICE_VOIDED',

  // Authorization surface
  'USER_CREATED',
  'USER_ROLE_CHANGED',
  'USER_DEACTIVATED',
  'USER_REACTIVATED',
  'PERMISSION_GRANTED',
  'PERMISSION_REVOKED',

  // Data protection compliance
  'DATA_EXPORT',
  'DATA_IMPORT',
  'CLIENT_RECORD_EXPORTED',
  'DOCUMENT_DOWNLOADED',
  'DOCUMENT_DELETED',
] as const;